name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Controle des dependances
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Test Dockerfile
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          scan-ref: 'Dockerfile'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
